export interface NamedColor {
  hex: string
  ru: string
  en: string
  family: string
}

// Серые и бежевые встречаются в реальном мире чаще всего — их здесь больше.
// [hex, русское название, английское название]
const groups: [string, [string, string, string][]][] = [
  ['серый', [
    ['#e6e6e3', 'Утренний туман', 'Morning Mist'],
    ['#dcdcd8', 'Гипсовый слепок', 'Plaster Cast'],
    ['#d3d4d2', 'Пепел от бумаги', 'Paper Ash'],
    ['#cfd3d6', 'Ноябрьское небо', 'November Sky'],
    ['#c8c8c4', 'Бетонная пыль', 'Concrete Dust'],
    ['#c0c4c8', 'Алюминиевая ложка', 'Aluminium Spoon'],
    ['#c5c0ba', 'Тёплый пепел', 'Warm Ash'],
    ['#bdb9b3', 'Речная галька', 'River Pebble'],
    ['#b8bcb6', 'Шалфейная дымка', 'Sage Haze'],
    ['#b5b5b0', 'Мокрый мел', 'Wet Chalk'],
    ['#aeb3b8', 'Голубиное крыло', 'Pigeon Wing'],
    ['#a9a9a4', 'Лунная пыль', 'Moon Dust'],
    ['#a2a7ab', 'Стальной трос', 'Steel Cable'],
    ['#9e9b95', 'Серая кошка', 'Grey Cat'],
    ['#9aa0a6', 'Потёртое серебро', 'Worn Silver'],
    ['#979a9c', 'Тротуарная плитка', 'Paving Stone'],
    ['#909090', 'Зимний полдень', 'Winter Noon'],
    ['#8a8f94', 'Грозовое облако', 'Thundercloud'],
    ['#868379', 'Сухой лишайник', 'Dry Lichen'],
    ['#808080', 'Нейтральная тень', 'Neutral Shadow'],
    ['#7a7e82', 'Мокрая черепица', 'Wet Roof Tile'],
    ['#75726c', 'Старый бетон', 'Old Concrete'],
    ['#707a80', 'Северное море', 'North Sea'],
    ['#6b6b68', 'Мышиная спинка', 'Mouse Back'],
    ['#666a6d', 'Свинцовая туча', 'Leaden Cloud'],
    ['#625e58', 'Вулканический песок', 'Volcanic Sand'],
    ['#5c6166', 'Шифер', 'Slate Roof'],
    ['#58585a', 'Гранитная крошка', 'Granite Grit'],
    ['#4f4c48', 'Остывший пепел костра', 'Cold Campfire Ash'],
    ['#4b4d50', 'Асфальт после дождя', 'Asphalt After Rain'],
    ['#474a4f', 'Графитовый стержень', 'Pencil Lead'],
    ['#434343', 'Чугунная сковорода', 'Cast-Iron Pan'],
    ['#3e4247', 'Ночной перрон', 'Night Platform'],
    ['#3a3835', 'Угольная пыль', 'Coal Dust'],
    ['#36393d', 'Ночная гроза', 'Night Storm'],
    ['#8c8a84', 'Старая монета', 'Old Coin'],
  ]],
  ['бежевый', [
    ['#f5efe3', 'Топлёное молоко', 'Baked Milk'],
    ['#f3e9dc', 'Ванильное мороженое', 'Vanilla Ice Cream'],
    ['#f0e6d2', 'Сливочный крем', 'Buttercream'],
    ['#eee6d4', 'Слоновая кость', 'Ivory'],
    ['#ede4d8', 'Рисовая бумага', 'Rice Paper'],
    ['#ebdcc2', 'Старая газета', 'Old Newspaper'],
    ['#e8d9bf', 'Льняная скатерть', 'Linen Tablecloth'],
    ['#e6dccf', 'Яичная скорлупа', 'Eggshell'],
    ['#e4d6c0', 'Мука грубого помола', 'Stone-Ground Flour'],
    ['#e3d3b8', 'Овсяные хлопья', 'Rolled Oats'],
    ['#e0cfae', 'Сухая солома', 'Dry Straw'],
    ['#dfd0b0', 'Лён после стирки', 'Washed Linen'],
    ['#ded3c4', 'Пергамент', 'Parchment'],
    ['#dcc9a8', 'Морской песок', 'Sea Sand'],
    ['#d9c8a9', 'Миндальное молоко', 'Almond Milk'],
    ['#d8c3a5', 'Молочная пенка', 'Milk Foam'],
    ['#d6c9b6', 'Холщовая сумка', 'Canvas Tote'],
    ['#d4bc98', 'Крафтовый конверт', 'Kraft Envelope'],
    ['#d2c4ae', 'Утренняя овсянка', 'Morning Porridge'],
    ['#cfb997', 'Верблюжья шерсть', 'Camel Hair'],
    ['#cdbfaa', 'Бумажный пакет', 'Paper Bag'],
    ['#cdb89a', 'Кешью', 'Cashew'],
    ['#cbb391', 'Пыльная дорога', 'Dusty Road'],
    ['#c9b28a', 'Сухой тростник', 'Dry Reed'],
    ['#c7ad8c', 'Кофе с молоком', 'Café au Lait'],
    ['#c4b6a1', 'Высохшая глина', 'Dried Clay'],
    ['#c2a883', 'Выгоревшая трава', 'Sunburnt Grass'],
    ['#bea37f', 'Обувная коробка', 'Shoebox'],
    ['#bda985', 'Джутовая верёвка', 'Jute Rope'],
    ['#bbac96', 'Мешковина', 'Burlap'],
    ['#b99c78', 'Винная пробка', 'Wine Cork'],
    ['#b3a283', 'Осенний камыш', 'Autumn Rushes'],
    ['#b2a38d', 'Дюна в тени', 'Shaded Dune'],
    ['#a99a84', 'Шампиньон', 'Button Mushroom'],
    ['#a89777', 'Выцветший хаки', 'Faded Khaki'],
    ['#a09079', 'Старая замша', 'Old Suede'],
  ]],
  ['белый', [
    ['#fbfbf8', 'Свежий снег', 'Fresh Snow'],
    ['#faf7f2', 'Взбитые сливки', 'Whipped Cream'],
    ['#f9f4ee', 'Фарфоровая чашка', 'Porcelain Cup'],
    ['#f8f6f0', 'Чистый лист', 'Blank Page'],
    ['#f7f3e8', 'Сахарная пудра', 'Powdered Sugar'],
    ['#f5f1e6', 'Хлопковая простыня', 'Cotton Sheet'],
    ['#f4f6f7', 'Иней на стекле', 'Frost on Glass'],
    ['#f2f0ea', 'Свежая штукатурка', 'Fresh Plaster'],
    ['#eef2f5', 'Лёд в стакане', 'Ice in a Glass'],
    ['#ecebe7', 'Тающий снег', 'Melting Snow'],
  ]],
  ['чёрный', [
    ['#0b0b0c', 'Безлунная ночь', 'Moonless Night'],
    ['#101418', 'Полночное озеро', 'Midnight Lake'],
    ['#141414', 'Типографская краска', 'Printer\'s Ink'],
    ['#181818', 'Мокрая резина', 'Wet Rubber'],
    ['#1a1a1d', 'Выключенный экран', 'Switched-Off Screen'],
    ['#1c1b1a', 'Древесный уголь', 'Charcoal'],
    ['#1e1f22', 'Вороново крыло', 'Raven Wing'],
    ['#222222', 'Старая покрышка', 'Old Tyre'],
    ['#231f20', 'Чернильная клякса', 'Ink Blot'],
    ['#2a2a2c', 'Печная сажа', 'Chimney Soot'],
  ]],
  ['коричневый', [
    ['#3b2a20', 'Остывший кофе', 'Cold Coffee'],
    ['#3f3129', 'Кофейная гуща', 'Coffee Grounds'],
    ['#43352c', 'Лесная подстилка', 'Forest Floor'],
    ['#4a3326', 'Горький шоколад', 'Dark Chocolate'],
    ['#4e3b31', 'Вспаханное поле', 'Ploughed Field'],
    ['#553025', 'Вишнёвая древесина', 'Cherry Wood'],
    ['#5a3d2b', 'Кора дуба', 'Oak Bark'],
    ['#5c4a3c', 'Мокрая земля', 'Wet Soil'],
    ['#5e3a2f', 'Мокрая кора вишни', 'Wet Cherry Bark'],
    ['#6b4430', 'Жареный каштан', 'Roasted Chestnut'],
    ['#6d5b4b', 'Старый чемодан', 'Old Suitcase'],
    ['#6f5643', 'Табачный лист', 'Tobacco Leaf'],
    ['#7a5c45', 'Сосновая шишка', 'Pine Cone'],
    ['#7b4a2e', 'Палочка корицы', 'Cinnamon Stick'],
    ['#826a55', 'Мускатный орех', 'Nutmeg'],
    ['#8a5a2b', 'Гречишный мёд', 'Buckwheat Honey'],
    ['#8a6a4f', 'Грецкий орех', 'Walnut'],
    ['#8b5a3c', 'Молочный шоколад', 'Milk Chocolate'],
    ['#8e4a2a', 'Ржавый гвоздь', 'Rusty Nail'],
    ['#937358', 'Осенняя тропа', 'Autumn Path'],
    ['#96643f', 'Жжёная карамель', 'Burnt Caramel'],
    ['#9c7b5c', 'Медовый пряник', 'Honey Cake'],
    ['#a0714f', 'Кожаная перчатка', 'Leather Glove'],
    ['#a38b72', 'Грибная шляпка', 'Mushroom Cap'],
    ['#a67b5b', 'Какао с молоком', 'Hot Cocoa'],
    ['#b08560', 'Корка багета', 'Baguette Crust'],
    ['#b89272', 'Имбирное печенье', 'Gingerbread'],
    ['#7d6450', 'Плетёная корзина', 'Wicker Basket'],
  ]],
  ['красный', [
    ['#f04e45', 'Раскалённый уголь', 'Glowing Ember'],
    ['#e8413a', 'Красный светофор', 'Red Light'],
    ['#e05a4f', 'Арбузная мякоть', 'Watermelon Flesh'],
    ['#e03c31', 'Спелая клубника', 'Ripe Strawberry'],
    ['#d9483b', 'Мак в поле', 'Field Poppy'],
    ['#d7261e', 'Пожарная машина', 'Fire Engine'],
    ['#cc3333', 'Томатный соус', 'Tomato Sauce'],
    ['#c7372f', 'Губная помада', 'Lipstick'],
    ['#c41e3a', 'Гранатовый сок', 'Pomegranate Juice'],
    ['#bf3b3b', 'Рябиновая гроздь', 'Rowan Berries'],
    ['#b5413a', 'Паприка', 'Paprika'],
    ['#b22222', 'Жгучий перец', 'Chilli Pepper'],
    ['#a52a2a', 'Кирпичная стена', 'Brick Wall'],
    ['#9b1b30', 'Бордо в бокале', 'Bordeaux in a Glass'],
    ['#962d2d', 'Ржавая крыша', 'Rusty Roof'],
    ['#8b1a1a', 'Спелая черешня', 'Ripe Cherry'],
    ['#8a2d2a', 'Вяленый томат', 'Sun-Dried Tomato'],
    ['#7a1f2b', 'Старое вино', 'Old Wine'],
    ['#6e1423', 'Вишнёвое варенье', 'Cherry Jam'],
    ['#5a1a1f', 'Запёкшаяся ягода', 'Baked Berry'],
  ]],
  ['розовый', [
    ['#ffd1dc', 'Лепесток сакуры', 'Cherry Blossom'],
    ['#f9d9d6', 'Щёки на морозе', 'Frosty Cheeks'],
    ['#f7c6c7', 'Зефир', 'Marshmallow'],
    ['#f4b6c2', 'Сахарная вата', 'Cotton Candy'],
    ['#f2a7b8', 'Розовый пион', 'Pink Peony'],
    ['#f5a3c7', 'Жевательная резинка', 'Bubblegum'],
    ['#eebfb6', 'Пудреница', 'Powder Compact'],
    ['#e8b4a0', 'Персиковый пушок', 'Peach Fuzz'],
    ['#e88ea3', 'Цветок шиповника', 'Wild Rose'],
    ['#e57a99', 'Фламинго', 'Flamingo'],
    ['#de6fa1', 'Цикламен', 'Cyclamen'],
    ['#d95f84', 'Малиновый джем', 'Raspberry Jam'],
    ['#d9a5a0', 'Пыльная роза', 'Dusty Rose'],
    ['#c98f8f', 'Засушенная роза', 'Dried Rose'],
    ['#c94c7a', 'Свекольный салат', 'Beet Salad'],
    ['#c77b86', 'Вишнёвый йогурт', 'Cherry Yogurt'],
    ['#b83a6b', 'Спелая малина', 'Ripe Raspberry'],
    ['#f0b8a8', 'Розовый грейпфрут', 'Pink Grapefruit'],
  ]],
  ['оранжевый', [
    ['#ffcc99', 'Дынная мякоть', 'Melon Flesh'],
    ['#ffb347', 'Курага', 'Dried Apricot'],
    ['#ffa500', 'Мандарин', 'Tangerine'],
    ['#ff9966', 'Лососевый стейк', 'Salmon Steak'],
    ['#ff7f11', 'Апельсиновая корка', 'Orange Peel'],
    ['#f7b27a', 'Спелый персик', 'Ripe Peach'],
    ['#f5a04a', 'Абрикос', 'Apricot'],
    ['#f4a261', 'Закат над морем', 'Sunset over the Sea'],
    ['#f28c28', 'Спелая тыква', 'Ripe Pumpkin'],
    ['#f08a5d', 'Коралл', 'Coral'],
    ['#e8752a', 'Морковный сок', 'Carrot Juice'],
    ['#e86a33', 'Облепиха', 'Sea Buckthorn'],
    ['#e59866', 'Хрустящая корочка', 'Golden Crust'],
    ['#e2692c', 'Терракотовый горшок', 'Terracotta Pot'],
    ['#d97a3a', 'Хурма', 'Persimmon'],
    ['#d35f2a', 'Лисий хвост', 'Fox Tail'],
    ['#c8642d', 'Осенний клён', 'Autumn Maple'],
    ['#b85c2c', 'Медный таз', 'Copper Basin'],
  ]],
  ['жёлтый', [
    ['#fff8b0', 'Первый луч', 'First Light'],
    ['#ffef9a', 'Лимонный крем', 'Lemon Curd'],
    ['#fff44f', 'Лимон', 'Lemon'],
    ['#ffe135', 'Банановая кожура', 'Banana Peel'],
    ['#ffd700', 'Одуванчик', 'Dandelion'],
    ['#f7e07a', 'Сливочное масло', 'Butter'],
    ['#f3d43b', 'Мимоза', 'Mimosa'],
    ['#f5c518', 'Подсолнух', 'Sunflower'],
    ['#f0c05a', 'Яичный желток', 'Egg Yolk'],
    ['#eedc82', 'Кукурузная каша', 'Polenta'],
    ['#e8b923', 'Мёд в сотах', 'Honeycomb'],
    ['#e6c86e', 'Пшеничное поле', 'Wheat Field'],
    ['#dab11c', 'Горчица', 'Mustard'],
    ['#d9d27e', 'Липовый цвет', 'Linden Blossom'],
    ['#d4af37', 'Церковный купол', 'Golden Dome'],
    ['#c9a227', 'Старое золото', 'Old Gold'],
    ['#b8961e', 'Нерафинированное масло', 'Unrefined Oil'],
    ['#9c7f1a', 'Бронзовая статуя', 'Bronze Statue'],
  ]],
  ['зелёный', [
    ['#dce8c8', 'Капустный лист', 'Cabbage Leaf'],
    ['#c5e1a5', 'Молодой салат', 'Young Lettuce'],
    ['#b2d8b2', 'Мятная жвачка', 'Mint Gum'],
    ['#a6e3a1', 'Весенний росток', 'Spring Sprout'],
    ['#b5c36b', 'Незрелый крыжовник', 'Unripe Gooseberry'],
    ['#a4b96e', 'Сельдерей', 'Celery'],
    ['#9bd94a', 'Кислый лайм', 'Sour Lime'],
    ['#9acd32', 'Весенняя трава', 'Spring Grass'],
    ['#93c572', 'Фисташка', 'Pistachio'],
    ['#8fbc8f', 'Эвкалипт', 'Eucalyptus'],
    ['#8f9a4c', 'Незрелая слива', 'Unripe Plum'],
    ['#7ba05b', 'Лист крапивы', 'Nettle Leaf'],
    ['#808000', 'Болотная кочка', 'Marsh Tussock'],
    ['#707b52', 'Лишайник на камне', 'Lichen on Stone'],
    ['#6b8e23', 'Оливка', 'Olive'],
    ['#6a8f6a', 'Шалфей', 'Sage'],
    ['#5b6e3a', 'Армейский рюкзак', 'Army Rucksack'],
    ['#556b2f', 'Хаки', 'Khaki'],
    ['#50a060', 'Свежий горошек', 'Fresh Peas'],
    ['#4f7942', 'Папоротник', 'Fern'],
    ['#4c5a3c', 'Мох в тени', 'Shaded Moss'],
    ['#4a7c59', 'Базилик', 'Basil'],
    ['#3cb371', 'Футбольный газон', 'Football Pitch'],
    ['#3b5323', 'Ночной лес', 'Night Forest'],
    ['#355e3b', 'Еловая хвоя', 'Spruce Needles'],
    ['#2e5e4e', 'Глубокий пруд', 'Deep Pond'],
    ['#228b22', 'Лесная поляна', 'Forest Clearing'],
    ['#1f4d2b', 'Бутылочное стекло', 'Bottle Glass'],
    ['#0f6b3f', 'Бильярдное сукно', 'Billiard Cloth'],
    ['#00a86b', 'Нефрит', 'Jade'],
  ]],
  ['бирюзовый', [
    ['#b7e4dc', 'Лёд ледника', 'Glacier Ice'],
    ['#a3d9d0', 'Морское стекло', 'Sea Glass'],
    ['#7fc8c0', 'Мятный леденец', 'Mint Candy'],
    ['#66cdaa', 'Аквамарин', 'Aquamarine'],
    ['#40e0d0', 'Лагуна', 'Lagoon'],
    ['#20b2aa', 'Бирюза', 'Turquoise'],
    ['#5f9ea0', 'Туман над заливом', 'Bay Fog'],
    ['#48a9a6', 'Бассейн в отеле', 'Hotel Pool'],
    ['#3a7d7c', 'Утиное перо', 'Duck Feather'],
    ['#2f8f83', 'Хвост павлина', 'Peacock Tail'],
    ['#008080', 'Морская волна', 'Sea Wave'],
    ['#00827f', 'Патина на бронзе', 'Bronze Patina'],
    ['#1b5e5a', 'Глубина фьорда', 'Fjord Depths'],
    ['#0d5c63', 'Ночной залив', 'Night Bay'],
  ]],
  ['голубой', [
    ['#d6ecf5', 'Утренняя дымка', 'Morning Haze'],
    ['#c6e2f0', 'Голубой фарфор', 'Blue Porcelain'],
    ['#bcd4e6', 'Тающий лёд', 'Thawing Ice'],
    ['#b0e0e6', 'Голубая лента', 'Blue Ribbon'],
    ['#add8e6', 'Утреннее небо', 'Morning Sky'],
    ['#a2c4d9', 'Зимнее небо', 'Winter Sky'],
    ['#9bc4e2', 'Льдинка', 'Ice Chip'],
    ['#89cff0', 'Детское одеяльце', 'Baby Blanket'],
    ['#87ceeb', 'Летнее небо', 'Summer Sky'],
    ['#7a9bbd', 'Выцветшие джинсы', 'Faded Jeans'],
    ['#6fa8dc', 'Незабудка', 'Forget-Me-Not'],
    ['#63a4c7', 'Морской горизонт', 'Sea Horizon'],
    ['#5dade2', 'Мыльный пузырь', 'Soap Bubble'],
    ['#4fb3d9', 'Горное озеро', 'Mountain Lake'],
    ['#3fa7d6', 'Крыло зимородка', 'Kingfisher Wing'],
    ['#00bfff', 'Ясный полдень', 'Clear Noon'],
  ]],
  ['синий', [
    ['#7b8fcc', 'Колокольчик', 'Bluebell'],
    ['#6495ed', 'Василёк', 'Cornflower'],
    ['#4a6fa5', 'Сумеречное небо', 'Dusk Sky'],
    ['#4b6584', 'Сизая дымка', 'Blue-Grey Smoke'],
    ['#5b7db1', 'Синяя тетрадь', 'Blue Notebook'],
    ['#4169e1', 'Синий бархат', 'Blue Velvet'],
    ['#3f5bc8', 'Ультрамарин', 'Ultramarine'],
    ['#3d5a80', 'Синий кит', 'Blue Whale'],
    ['#3b5ba5', 'Школьная форма', 'School Uniform'],
    ['#34495e', 'Грозовое море', 'Stormy Sea'],
    ['#2c3e50', 'Тёмная вода', 'Dark Water'],
    ['#2a52be', 'Синяя ручка', 'Ballpoint Blue'],
    ['#2451a3', 'Синяя изолента', 'Blue Electrical Tape'],
    ['#26428b', 'Новые джинсы', 'New Denim'],
    ['#1f4e79', 'Глубокое море', 'Deep Sea'],
    ['#1e3a8a', 'Ночное небо', 'Night Sky'],
    ['#1b3a6b', 'Черника в корзине', 'Basket of Blueberries'],
    ['#1c2b4a', 'Небо перед рассветом', 'Sky Before Dawn'],
    ['#0f52ba', 'Сапфир', 'Sapphire'],
    ['#0047ab', 'Кобальт', 'Cobalt'],
    ['#0a3161', 'Ночное море', 'Night Sea'],
    ['#002147', 'Бушлат моряка', 'Sailor\'s Peacoat'],
    ['#191970', 'Полночь', 'Midnight'],
    ['#000080', 'Чернила', 'Ink'],
  ]],
  ['фиолетовый', [
    ['#e0b0ff', 'Лиловый леденец', 'Lilac Lollipop'],
    ['#dda0dd', 'Цветок сливы', 'Plum Blossom'],
    ['#d8bfd8', 'Чертополох', 'Thistle'],
    ['#c8a2c8', 'Сиреневый туман', 'Lilac Mist'],
    ['#b39ddb', 'Сирень в мае', 'May Lilac'],
    ['#9b87c4', 'Лавандовое поле', 'Lavender Field'],
    ['#9966cc', 'Аметист', 'Amethyst'],
    ['#9a6b93', 'Вереск', 'Heather'],
    ['#915f6d', 'Пожухлая сирень', 'Faded Lilac'],
    ['#8e44ad', 'Ежевичный сок', 'Blackberry Juice'],
    ['#b048b5', 'Орхидея', 'Orchid'],
    ['#c71585', 'Фуксия', 'Fuchsia'],
    ['#a23b72', 'Свекольный сок', 'Beet Juice'],
    ['#800080', 'Царская мантия', 'Royal Robe'],
    ['#7851a9', 'Ирис', 'Iris'],
    ['#6e5b8f', 'Дымчатый аметист', 'Smoky Amethyst'],
    ['#673147', 'Шелковица', 'Mulberry'],
    ['#5e3a64', 'Спелая слива', 'Ripe Plum'],
    ['#4b2a3f', 'Баклажан', 'Aubergine'],
    ['#4b0082', 'Индиго', 'Indigo'],
    ['#3c2a54', 'Фиолетовые сумерки', 'Violet Dusk'],
    ['#2e1a47', 'Ежевика', 'Blackberry'],
  ]],
]

export const COLORS: NamedColor[] = groups.flatMap(([family, list]) =>
  list.map(([hex, ru, en]) => ({ hex, ru, en, family })),
)
